{{Header}}

using System;
using System.Threading.Tasks;
using {{ProjectName}}.Models.{{ModelNamePlural}};
using {{ProjectName}}.Models.{{ModelNamePlural}}.Exceptions;
using FluentAssertions;
using Microsoft.Data.SqlClient;
using Moq;
using Xunit;

namespace {{NameSpace}}
{
    public partial class {{ModelName}}ServiceTests
    {
        [Fact]
        public async Task ShouldThrowCriticalDependencyExceptionOnRetrieveByIdIfSqlErrorOccursAndLogItAsync()
        {
            //given
            Guid someId = Guid.NewGuid();
            SqlException sqlException = CreateSqlException();

            var failed{{ModelName}}StorageException =
                new Failed{{ModelName}}StorageException(sqlException);

            var expected{{ModelName}}DependencyException =
                new {{ModelName}}DependencyException(failed{{ModelName}}StorageException);

            this.storageBrokerMock.Setup(broker =>
                broker.Select{{ModelName}}ByIdAsync(It.IsAny<Guid>()))
                    .ThrowsAsync(sqlException);

            //when
            ValueTask<{{ModelName}}> retrieve{{ModelName}}ByIdTask =
                this.{{modelName}}Service.Retrieve{{ModelName}}ByIdAsync(someId);

            {{ModelName}}DependencyException actual{{ModelName}}Dependencyexception =
                await Assert.ThrowsAsync<{{ModelName}}DependencyException>(
                    retrieve{{ModelName}}ByIdTask.AsTask);

            //then
            actual{{ModelName}}Dependencyexception.Should().BeEquivalentTo(
                expected{{ModelName}}DependencyException);

            this.storageBrokerMock.Verify(broker =>
                broker.Select{{ModelName}}ByIdAsync(It.IsAny<Guid>()), Times.Once);

            this.loggingBrokerMock.Verify(broker =>
                broker.LogCritical(It.Is(SameExceptionAs(
                    expected{{ModelName}}DependencyException))), Times.Once);

            this.storageBrokerMock.VerifyNoOtherCalls();
            this.loggingBrokerMock.VerifyNoOtherCalls();
            this.dateTimeBrokerMock.VerifyNoOtherCalls();
        }

        [Fact]
        public async Task ShouldThrowServiceExceptionOnRetrieveByIdAsyncIfServiceErrorOccursAndLogItAsync()
        {
            //given
            Guid someId = Guid.NewGuid();
            var serviceException = new Exception();

            var failed{{ModelName}}ServiceException =
                new Failed{{ModelName}}ServiceException(serviceException);

            var expected{{ModelName}}ServiceException =
                new {{ModelName}}ServiceException(failed{{ModelName}}ServiceException);

            this.storageBrokerMock.Setup(broker =>
                broker.Select{{ModelName}}ByIdAsync(It.IsAny<Guid>())).ThrowsAsync(serviceException);

            //when
            ValueTask<{{ModelName}}> retrieve{{ModelName}}ByIdTask =
                this.{{modelName}}Service.Retrieve{{ModelName}}ByIdAsync(someId);

            {{ModelName}}ServiceException actual{{ModelName}}ServiceException =
                await Assert.ThrowsAsync<{{ModelName}}ServiceException>(retrieve{{ModelName}}ByIdTask.AsTask);

            //then
            actual{{ModelName}}ServiceException.Should().BeEquivalentTo(expected{{ModelName}}ServiceException);

            this.storageBrokerMock.Verify(broker =>
                broker.Select{{ModelName}}ByIdAsync(It.IsAny<Guid>()), Times.Once);

            this.loggingBrokerMock.Verify(broker =>
                broker.LogError(It.Is(SameExceptionAs(
                    expected{{ModelName}}ServiceException))), Times.Once);

            this.storageBrokerMock.VerifyNoOtherCalls();
            this.loggingBrokerMock.VerifyNoOtherCalls();
            this.dateTimeBrokerMock.VerifyNoOtherCalls();
        }
    }
}